workflows:
  ios-project-workflow:
    name: Xcode iOS Simulator Build
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      xcode: latest
    scripts:
      - name: Build App for Simulator
        script: |
          xcodebuild clean build -project "Lab14IntroFirebase.xcodeproj" \
            -scheme "Lab14IntroFirebase" \
            -sdk iphonesimulator \
            -configuration Debug \
            -arch x86_64 \
            CODE_SIGNING_ALLOWED=NO
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app